### ISSUE TITLE
An animated, interactive character

### ISSUE THREAD

**Issue by a1an-huang** [a1an-huang/CSE380-GROUP-FINAL-PROJECT#10]
Define your primary character (or characters or units, depending on game genre) including its movements and interactions such that it is fully animated and may move about the game world as desired. Note that if your game has a main character, then this should be that character. If your game is a puzzle game or something different that doesn't have a main character, this should be some dynamic element in the game to demostrate animation.

**Comment by Chen1571** [comment]
Benchmark 2 assignment description
