### ISSUE TITLE
[TODO] Finish tilemaps for level 1 and 2

### ISSUE THREAD

**Issue by Chen1571** [a1an-huang/CSE380-GROUP-FINAL-PROJECT#49]
I am not sure if the tilemaps are finalized for the first 2 levels, but just check them off here when they are. So far, the level 1 tilemap is a little messy according to my friends who test out the game. Maybe make it a little more of a linear progression for the first level compared to a maze structure.

- [ ] Finish level 1 tilemap
- [ ] Finish level 2 tilemap

**Comment by rsarker1** [comment]
Need to playtest level 1 and add ice powerup but other than that its done.

**Comment by Chen1571** [comment]
Level1 and Level2 are basically done, enhancements can be done in the future
