### ISSUE TITLE
Core Game Mechanics 

### ISSUE THREAD

**Issue by a1an-huang** [a1an-huang/CSE380-GROUP-FINAL-PROJECT#7]
in a video game, core gameplay mechanics refers to the things the player will be doing over and over and over again while playing. If this core mechanic is not fun or interesting or burdensome, the game is doomed. In this assignment you must demonstrate the core mechanics of gameplay. If you have a main character then that means the movements and abilities of that character as it interacts with its game environment. Note again that a large part of your grade in this project will be based on whether the game is fun or not, so you need to start working out the fun aspect of play in this assignment. While playing this first build, think about how you could improve the player-to-character symbiosis to make core gameplay more fun and interesting.

**Comment by Chen1571** [comment]
Benchmark 2 assignment description
