### ISSUE TITLE
Complete User Interface

### ISSUE THREAD

**Issue by a1an-huang** [a1an-huang/CSE380-GROUP-FINAL-PROJECT#8]
Implement the mockups you created in benchmark 1, fully creating a nice, well organized, working user interface that suits your game. Navigation should work completely, and you should have your Level Select, Controls, and Help screens up and running as well as your in-game User Interface.

**Comment by a1an-huang** [comment]
Todo List:
- [ ] Level Select
- [ ]  Controls Screen
- [ ] Help Screen
- [ ] In-Game User Interface
- [ ] Page Navigation

**Comment by Chen1571** [comment]
I added the screens/transitions for main menu, level select, controls, and help.
Just put placeholder stuff from figma

**Comment by Chen1571** [comment]
Benchmark 2 assignment description
