### ISSUE TITLE
World Rendering

### ISSUE THREAD

**Issue by a1an-huang** [a1an-huang/CSE380-GROUP-FINAL-PROJECT#9]
Implement all the design, layout and rendering of the first level, which should be an introductory level that acclaimates the player to gameplay. Remember, your team will need two levels for each team member, the assumption is that each teammate should be a level designer for two levels. In this benchmark, you should also start a partial implementation of each level. As such, you'll have to think about:
Level Editing Tool to use (can be [Tiled](http://www.mapeditor.org/) or some other tool, including your own custom tool)
File format for levels
Commonality between levels. What is shared, what is unique
Level Functionality. What is shared, what is unique.

**Comment by Chen1571** [comment]
Benchmark 2 assignment description
